import { Disclosure } from '@/components/playground/Disclosure';
import { Tabs, Tab } from '@/components/playground/Tabs';
import { Modal } from '@/components/playground/Modal';

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog"
import { Tabs as ShadcnTabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"

export const metadata = {
  title: 'Accessibility Playground',
};

export default function PlaygroundPage() {
  const tabsData: Tab[] = [
    {
      id: 'tab-1',
      label: 'React',
      content: <p>React is a JavaScript library for building user interfaces.</p>,
    },
    {
      id: 'tab-2',
      label: 'TypeScript',
      content: <p>TypeScript is a strongly typed programming language that builds on JavaScript.</p>,
    },
    {
      id: 'tab-3',
      label: 'Next.js',
      content: <p>Next.js is a React framework for building full-stack web applications.</p>,
    },
  ];

  return (
    <main className="max-w-3xl mx-auto p-8">
      <h1 className="text-3xl font-bold mb-8">Accessibility Playground</h1>
      <p className="mb-8 text-gray-700">
        This page demonstrates manual implementations of accessible interactive components.
      </p>

      <section className="mb-12">
        <h2 className="text-2xl font-semibold mb-4">1. Disclosure</h2>
        <p className="text-sm text-gray-600 mb-4">
          <strong>Keyboard:</strong> Use <kbd>Tab</kbd> to focus, and <kbd>Enter</kbd> or <kbd>Space</kbd> to toggle the content.
        </p>
        <Disclosure title="What is Web Accessibility?">
          <p>
            Web accessibility means that websites, tools, and technologies are designed and developed so that people with disabilities can use them.
          </p>
        </Disclosure>
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-semibold mb-4">2. Tabs (Manual Activation)</h2>
        <p className="text-sm text-gray-600 mb-4">
          <strong>Keyboard:</strong> Use <kbd>Tab</kbd> to enter the tablist. Use <kbd>Arrow</kbd> keys to move focus between tabs. Press <kbd>Enter</kbd> or <kbd>Space</kbd> to select the focused tab. <kbd>Home</kbd> and <kbd>End</kbd> go to the first and last tabs.
        </p>
        <Tabs tabs={tabsData} ariaLabel="Technologies" />
      </section>

      <section className="mb-12">
        <h2 className="text-2xl font-semibold mb-4">3. Modal Dialog</h2>
        <p className="text-sm text-gray-600 mb-4">
          <strong>Keyboard:</strong> Use <kbd>Tab</kbd> to focus the trigger and <kbd>Enter</kbd> or <kbd>Space</kbd> to open. Inside the modal, focus is trapped. <kbd>Tab</kbd> moves forward, <kbd>Shift</kbd>+<kbd>Tab</kbd> moves backward. Press <kbd>Escape</kbd> to close.
        </p>
        
        <div className="flex flex-col gap-4 items-start">
          <a href="#" className="text-blue-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 rounded px-1">
            Focusable element before modal
          </a>
          
          <Modal triggerText="Open Settings" title="Account Settings">
            <p className="mb-4">
              Here you can update your account preferences.
            </p>
            <div className="flex flex-col gap-2">
              <label htmlFor="username" className="text-sm font-medium">Username</label>
              <input 
                id="username" 
                type="text" 
                className="border border-gray-300 rounded px-3 py-2 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500" 
                defaultValue="johndoe"
              />
            </div>
          </Modal>

          <button type="button" className="text-blue-600 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 rounded px-1">
            Focusable element after modal
          </button>
        </div>
      </section>
      <hr className="my-12 border-gray-300" />
      <h2 className="text-3xl font-bold mb-8">Shadcn / Base UI Implementations</h2>
      <p className="mb-8 text-gray-700">
        These components are generated by shadcn/ui and use @base-ui/react primitives. Check out <code>playground/NOTES.md</code> for a comparison of features and gaps.
      </p>

      <section className="mb-12">
        <h3 className="text-xl font-semibold mb-4">Shadcn Tabs</h3>
        <ShadcnTabs defaultValue="tab-1" className="w-[400px]">
          <TabsList>
            <TabsTrigger value="tab-1">React</TabsTrigger>
            <TabsTrigger value="tab-2">TypeScript</TabsTrigger>
            <TabsTrigger value="tab-3" disabled>Next.js (Disabled)</TabsTrigger>
          </TabsList>
          <TabsContent value="tab-1">React is a JavaScript library for building user interfaces.</TabsContent>
          <TabsContent value="tab-2">TypeScript is a strongly typed programming language that builds on JavaScript.</TabsContent>
          <TabsContent value="tab-3">Next.js is a React framework for building full-stack web applications.</TabsContent>
        </ShadcnTabs>
      </section>

      <section className="mb-12">
        <h3 className="text-xl font-semibold mb-4">Shadcn Dialog</h3>
        <Dialog>
          <DialogTrigger render={<Button variant="outline" />}>
            Open Shadcn Dialog
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Account Settings</DialogTitle>
              <DialogDescription>
                This dialog uses a Portal to render at the document root, avoiding stacking context issues.
              </DialogDescription>
            </DialogHeader>
            <div className="py-4">
              <label htmlFor="shadcn-username" className="text-sm font-medium">Username</label>
              <input 
                id="shadcn-username" 
                type="text" 
                className="border border-gray-300 rounded px-3 py-2 w-full mt-2" 
                defaultValue="johndoe"
              />
            </div>
          </DialogContent>
        </Dialog>
      </section>
    </main>
  );
}
