import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <header className="border-b border-border bg-background sticky top-0 z-10">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex justify-between h-16 items-center">
              <div className="flex">
                <Link href="/" className="flex-shrink-0 flex items-center font-bold text-xl text-primary">
                  Hit.AI
                </Link>
                <nav className="hidden sm:ml-8 sm:flex sm:space-x-4">
                  <Link href="/analysis" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Analysis</Link>
                  <Link href="/prioritize" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Prioritize</Link>
                  <Link href="/applications" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Applications</Link>
                  <Link href="/cover-letter" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Cover Letter</Link>
                  <Link href="/linkedin" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">LinkedIn</Link>
                  <Link href="/interview" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Interview</Link>
                  <Link href="/health" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Health</Link>
                </nav>
              </div>
              {/* Mobile Menu simple button logic would need Client Component, but we can just show a simpler menu or use CSS. 
                  Given "Server Components by default", I'll use a CSS-only solution or just make it horizontally scrollable on mobile. */}
            </div>
            {/* Mobile horizontal scrolling nav */}
            <div className="sm:hidden pb-3 overflow-x-auto whitespace-nowrap scrollbar-hide">
              <nav className="flex space-x-4">
                  <Link href="/analysis" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Analysis</Link>
                  <Link href="/prioritize" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Prioritize</Link>
                  <Link href="/applications" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Applications</Link>
                  <Link href="/cover-letter" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Cover Letter</Link>
                  <Link href="/linkedin" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">LinkedIn</Link>
                  <Link href="/interview" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Interview</Link>
                  <Link href="/health" className="text-muted-foreground hover:text-foreground px-3 py-2 rounded-md text-sm font-medium">Health</Link>
              </nav>
            </div>
          </div>
        </header>
        <main className="flex-1 flex flex-col">{children}</main>
      </body>
    </html>
  );
}
